bmi-soilgrids:
  service_id: {{service_id}}
  coverage_id: {{coverage_id}}
  crs: {{crs}}
  west: {{west}}
  south: {{south}}
  east: {{east}}
  north: {{north}}
  resx: {{resx}}
  resy: {{resy}}
  width: {{width}}
  height: {{height}}
  response_crs: {{response_crs}}
  output: {{output}}
